### PR TITLE
#97 Fix: diffhtml do not applying checkbox checked

### PR DESCRIPTION
**Pull request by jmas**
Issue #97.

### CODE REVIEW

**Comment by tbranyen** [comment]
Sorry, I haven't gotten around to writing the test yet. I'm doing some really tedious and annoying source porting at work. I'm planning on writing it on the shuttle ride home!

**Comment by jmas** [comment]
@tbranyen Thanks a lot about your attention about this issue.

**Comment by tbranyen** [comment]
So @jmas this is the test I wrote:

``` js
    it.only('can toggle boolean attributes like checked', function() {
      diff.innerHTML(this.fixture, '<input checked>');
      assert.equal(this.fixture.firstChild.checked, true);
      diff.innerHTML(this.fixture, '<input>');
      assert.equal(this.fixture.firstChild.checked, false);
    });
```

And it passes with or without this patch. This leads me to believe that it's specific to the tagged template feature. Which ends up generating an attribute like: `name: '', value: ''`.

I'll work on a test for that next.

**Comment by jmas** [comment]
@tbranyen  Yep, looks like tests are looks right.

Looks like `radio` buttons is do not work too. I played with diffhtml source and note that if I add `if (!newAttr || !newAttr.name)` then I see that Input DOM Element `checked` attribute is add/remove correctly, but visually nothing is happens (actually for `<input type="radio" />`). I found an W3C spec where telling that we should work with `checked` property as boolean: to set/unset it in this way: `el.checked = true / false`. Maybe this information can helps.

Please look on this ToDo app preview (not patched): https://jmas.github.io/gist/?2c06459138e4f8db74691b663750b196 (code for it there: https://github.com/jmas/htmldiff-todo).

And this ToDo (with patched htmldiff with my PR): https://jmas.github.io/gist/?522bfedb22af7ebd088bfbcae03d1a83 (inputs with type `checkbox` is working correctly, but `radio` is still not working).

**Comment by tbranyen** [comment]
@jmas okay i just tested and you're right its not working there. However, I'm not seeing any tagged template calls in the source, are you by chance using the babel transpiler in these examples?

**Comment by tbranyen** [comment]
Specifically are you using https://github.com/tbranyen/transform-tagged-diffhtml?

**Comment by jmas** [comment]
@tbranyen Yes, you right. I using it. [Here](https://github.com/jmas/htmldiff-todo/blob/master/src/ui.js#L55) is line how I add `checked` attribute.

Btw, I added [an issue](https://github.com/tbranyen/transform-tagged-diffhtml/issues/4) for `transform-tagged-diffhtml`.

**Comment by tbranyen** [comment]
Awesome thanks. tbqh I haven't put much work into the transform yet, it works most of the time, but there could definitely be side effects like this. I'm going to merge my tests for the checked input state, and then we can investigate on the transform side why this isn't working right.

Btw, thanks for sticking with this, it really helps make diffHTML better when more people than myself and Netflix are using it haha.

**Pull request merged**
