### PR TITLE
Remove unused example file, menu.html

### PR DESCRIPTION
**Pull request by jmeas**

### CODE REVIEW

**Comment by tbranyen** [comment]
Hey @jmeas can you check out the rewrite-amd branch here: https://github.com/tbranyen/diffhtml/tree/rewrite-amd, I think this is the direction I'm going. Less error prone since there are no source maps necessary and easier to unit test.

**Comment by jmeas** [comment]
Interesting...moving from ES2015 => AMD? I can understand why...it can be a real pain to get everything set up to work with Babel. What specific issues were you having with unit testing that led you to decide to rewrite this in AMD?

**Comment by tbranyen** [comment]
I couldn't figure out how to unit test browser stuff and get accurate code coverage. I never got accurate source map alignment when debugging. I was doing some weird hacks to account for how Babel transpiles to ES5 (less important). For this particular project I care more about accuracy of what's run and strictly testing it, I'd rather not transpile the code.

Although, if we could figure out how to test diffHTML in a browser and get perfect code coverage reporting, I'd backport all my changes in there to the ES6 branch.

**Comment by jmeas** [comment]
> Although, if we could figure out how to test diffHTML in a browser and get perfect code coverage reporting, I'd backport all my changes in there to the ES6 branch.

I think that **should** be doable, though it'd be much easier for me to set it up using `gulp`. Also, seeing as how master is already ES2015-ified, it'd be easier to start there.

If I put together a Gulp branch off of master that allows for testing in the browser + coverage reporting + accurate source maps, would you be up for merging that?

**Comment by tbranyen** [comment]
Yes, absolutely!

**Comment by tbranyen** [comment]
I have no issues w/ Gulp, so feel free to use that.

**Comment by jmeas** [comment]
Gonna close this PR, 'cause it seems irrelevant based on current work, and then open a new issue to track the ES2015 updates.

**Pull request closed without merging**
