### PR TITLE
Internals rewrite

### PR DESCRIPTION
**Pull request by tbranyen**
## Changes:

Transactions
-----------------

This creates a new way to render diffHTML by flowing tasks through a transaction. Transactions are like deferreds, only abortable. Each task gets called with a single argument which is a `transaction` instance.  Middleware are part of this transaction flow. They are called during the start of a transaction and can react to the completed transaction state. This makes it ideal for logging, web sockets, dev tools, testing, and any number of potential transformations for the code.

Check out the [lib/tasks](https://github.com/tbranyen/diffhtml/tree/transaction-flow/lib/tasks) folder to see each stage of diffHTML rendering.

Tree
------

A Virtual Tree Element is now the only pooled object in diffHTML. Attributes have been changed from being an array of pooled objects, to being a simple attribute object. This has had numerous benefits across the library, since users will generally want to work with an object, not an array.

#### Creating a tree

It is now significantly easier to create a virtual tree using the `createTree` method. This works very similar to React's `createElement` method. An example:

``` js
import { createTree, innerHTML } from 'diffhtml';

const statelessComponent = props => createTree('main', [
  createTree('div', 'Hello world!'),
  createTree('input', { value: 'High five', onclick: ev => console.log(ev), }),
]);

innerHTML(document.body, statelessComponent);
```

- [x] Full JSX support
- [X] Transactions rewrite + tests
- [x] Tree rewrite + tests
- [x] Node rewrite + tests
- [x] Transitions rewrite + tests
- [ ] Parsing strict mode (closer to JSX/XML, no unclosed tags, no unclosed attributes, etc.)

### CODE REVIEW

**Comment by tbranyen** [comment]
Tests are gonna be very broken right now, I'm still working out some kinks and refactoring.

**Comment by tbranyen** [comment]
Note: I'm working on so many diffHTML related projects at once to prep them for 1.0, so this branch may get some weird/broken commits while I'm testing out things.

On the horizon:

- diffHTML - 1.0 stable w/ JSX support & mono repo (will happen right before release)
- Chrome DevTools - Manipulate/visualize internals
- Logging - Output render states
- Components - Create React compatible Web or Simple (no custom el) stateful components
- Inline transitions - Bind transition callbacks like normal DOM events
- Verify state (aka sanity) - Logs out differences between the DOM and diffHTML's synchronization logic
- Synthetic events - By default diffHTML binds inline, this binds global handlers and delegation (supports all non-bubbling events as well)

On the not-so-near horizon:

- Full React compatibility via `diffhtml-react-compat`
- Web Workers using new middleware API
- Hooks & Middleware API in DevTools to make custom panes for reports

**Comment by mAAdhaTTah** [comment]
I'm currently using `morphdom` in the framework I'm building, [`brookjs`](https://github.com/valtech-nyc/brookjs), but I've been watching this project as well and there a number of ideas coming in here that dovetail quite well with what I'd like to accomplish with the framework. I think the major difference between what you're doing and what I'd like to do is the underlying abstraction is the Observable, vs the Transaction class you've built here.

I'm also really intrigued by the middleware concept here, and I was wondering if you'd be open to chatting about how our projects might mesh.

Happy to shoot you an email if that's a better place to continue the convo.

**Comment by tbranyen** [comment]
@mAAdhaTTah Awesome! That sounds great to me. Email and Gitter work for me: https://gitter.im/tbranyen/diffhtml. BTW I wrote the transaction flow so that the last task (most likely middleware) informs the return value. So right now I have [`end-as-promise`](https://github.com/tbranyen/diffhtml/blob/transaction-flow/lib/tasks/end-as-promise.js), you can see it won't be too complex to handle an observable either.

**Comment by tbranyen** [comment]
Going to merge this in. The PR is huge and I want to focus on individual areas of the code again before going to 1.0.

**Pull request merged**
