### PR TITLE
Updated regexp to properly handle dot in attribute name

### PR DESCRIPTION
**Pull request by rzhornyk**

### CODE REVIEW

**Comment by tbranyen** [comment]
Good find, turns out diffHTML is missing a bunch of valid characters in HTML attribute names. I'm traveling right now, but I would suspect that we need to add what isn't valid, vs what is in this case.

**Comment by rzhornyk** [comment]
So as I see according to spec https://html.spec.whatwg.org/multipage/syntax.html#attributes-2
next regexp can be used:
```
/\b([^\s\x00-\x1F"'>\/=\uFDD0-\uFDEF\uFFFE\uFFFF]*)\s*(=\s*("([^"]+)"|'([^']+)'|(\S+)))?/ig
```
What do you think?

**Comment by tbranyen** [comment]
I tried this regex out and while it looks almost identical to the one we currently use, it is causing 1-more tests to hang indefinitely. Very strange. Will investigate more and try to get this landed soon.

**Comment by tbranyen** [comment]
Found numerous tests which fail, but this one failed first and seems relevant to this issue (attribute matching). Seems that attribute matching was used for interpolated dynamic value as well, and the regex was less strict allowing for a `__STYLE_VALUE__` used as interpolation tokens.

```js
  it('will interpolate value-less attributes', function() {
    const checked = 'checked';
    const input = html`<input type="checkbox" ${checked}>`;

    equal(input.attributes.checked, 'checked');
  });
```

Which causes an infinite loop:

```js
[ '',
  '',
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  index: 31,
  input: 'type="checkbox" __DIFFHTML__0__',
  groups: undefined ]
```

I think this regex is too complex and we need to simplify it for the needs of the parser, which is meant to operate more loosely.  We do have a strict mode, and could potentially toggle the regex between modes.

**Comment by tbranyen** [comment]
Declining in favor of #207 which updates using the regex matching provided in your comment above @rzhornyk. Thanks for bringing up the issue!

**Pull request closed without merging**
