### PR TITLE
fall back to sync code if webworker creation fails

### PR DESCRIPTION
**Pull request by Egis-Moshe**

### CODE REVIEW

**Comment by tbranyen** [comment]
Can you remove the console.error in favor of either info or nothing at all.  Is it usefuo to know the worker wasn't created?

**Comment by tbranyen** [comment]
Why did you close this PR?

**Comment by tbranyen** [comment]
@Egis-Moshe you can simply push changes into your branch and the PR will update automatically, no need to close and open a new one

**Comment by Egis-Moshe** [comment]
I closed and opened a new PR so as not to pollute the commit history..

**Comment by tbranyen** [comment]
@Egis-Moshe I would recommend rebasing your local branch and force pushing upstream to avoid any pollution.  It's noiser to open and close many PRs for the same exact thing.

**Pull request closed without merging**
