### PR TITLE
Remove Web Workers and Custom Elements

### PR DESCRIPTION
**Pull request by tbranyen**
Experimenting with removing code around lesser used features in order to tighten up the library API surface area.

### CODE REVIEW

**Comment by tbranyen** [comment]
I know I argued a ton that Web Workers are important and not too hard to implement, but unfortunately there is too much of a negative impact on the codebase by including this feature.

**Comment by tbranyen** [comment]
If this turns out to be a mistake, I can always revert, it's not the end of the world.

**Comment by jmeas** [comment]
What's the new minified/gzip size?

**Comment by tbranyen** [comment]
@jmeas here are the latest numbers as of version 0.8.0:

-rw-r--r-- 1 tim  73K May 16 00:54 diffhtml.js
-rw-r--r-- 1 tim 9.8K May 16 01:06 diffhtml.min.gzip.js.gz
-rw-r--r-- 1 tim  43K May 16 01:06 diffhtml.min.js

**Pull request merged**
