### PR TITLE
Component tests and Shared Internals

### PR DESCRIPTION
**Pull request by tbranyen**
Been messing around with a module `diffhtml-shared-internals` that exposes internal diffHTML methods, properties, values, etc. I had to use a Babel plugin to remap the imports for ES and CJS environments. This will pave the way forward for future integration in both paths. I updated the package manifests in both to contain `esnext:main`.

I've started rewriting the web components implementations. Tests are being added along side them. Will continue to add and improve to them until they are both feature parity with React proper.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
This resolves #127?

**Comment by mAAdhaTTah** [comment]
FYI, `prop-types` is the one shipped by the `react` team; `proptypes` is a userland extraction.

**Comment by tbranyen** [comment]
@mAAdhaTTah Yeah I originally started this work before `prop-types` existed and now I gotta decide which one to stick with. `proptypes` is easier to invoke than `prop-types`, but I should probably stick with the React-leaning one.

**Comment by tbranyen** [comment]
@mAAdhaTTah i think so, i need to finish rolling out the cjs/es builds to the remaining modules and ensure all the middleware work with the new shared-internals

**Comment by mAAdhaTTah** [comment]
Some more questions:

On this "ES Modules" support, it looks like you're gearing that towards being able to be loaded in the browser. The `shared-internals` package points to `../diffhtml` rather than `diffhtml`. Is this going to have issues w/ node/Webpack?

Also, any chance you can publish a beta to npm? Would love to update my lib to use the new internals and make sure my tests pass.

**Comment by tbranyen** [comment]
Which modules do you need a beta for? I'll shoot for publishing some stuff today.

**Comment by mAAdhaTTah** [comment]
The main `diffhtml` & the `shared-internals`. Not using the others (yet).

**Comment by tbranyen** [comment]
There could definitely be issues (with the es build), and my logic for the scoping to top isn't perfect yet. I'm only adding (../).

**Comment by mAAdhaTTah** [comment]
@tbranyen I'll be around today on gitter if you need me.

**Pull request merged**
