### PR TITLE
React compatibility

### PR DESCRIPTION
**Pull request by tbranyen**
Goals of this PR are to make React compatibility more of a reality. Work has already been started and very little is remaining of overall surface area.

https://facebook.github.io/react/docs/react-api.html

What works today:

- ES6 class component definition
- Rendering JSX
- All lifecycle events
- `setState`
- `forceUpdate`
- `createElement`
- `isValidElement`
- `Children`

What is missing:

- [x] [Context](https://facebook.github.io/react/docs/context.html)
- [x] [PureComponent](https://facebook.github.io/react/docs/react-api.html#react.purecomponent)
- [x] [`createFactory`](https://facebook.github.io/react/docs/react-api.html#createfactory)
- [x] [`cloneElement`](https://facebook.github.io/react/docs/react-api.html#cloneelement)

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Is context even worth implementing, given how experimental the API is?

**Comment by tbranyen** [comment]
Super useful IMO (Esp. given the goal of React interop). They will solidify the API eventually and if they make breaking changes, it won't be hard for us to follow.

**Comment by tbranyen** [comment]
Been super busy at work and with life stuff. I got context working, but had test casualties in the process. `createFactory` and `cloneElement` will take longer to write tests for than to implement so this should be closed before August.

**Comment by tbranyen** [comment]
I'm going to leave the WebComponent tests for a different day. Gonna merge this as-is. Should be completely backwards compatible.

**Pull request merged**
